import Head from "next/head";

const Blogs = () => {
    return (
        <>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="text-6xl font-bold">
                This is blog page
            </div>
        </>

    );
};

export default Blogs;