import Head from "next/head";
const Blogs = ({ myData, setmyData }: any, { itemsList }: any) => {
    console.log(myData);
    // setmyData(itemsList)

    return (
        <>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="text-6xl font-bold">
                This is blog page
            </div>
        </>

    );
};

export const getServerSideProps = async () => {
    const res = await fetch(`https://jsonplaceholder.typicode.com/users`);
    const itemsList = await res.json();

    return {
        props: {
            itemsList
        }
    }
}

export default Blogs;